### PR TITLE
Say hello to BORS

### PR DESCRIPTION
**Pull request by imkiva**
Files are copied and adapted from https://github.com/aya-prover/aya-dev

### CODE REVIEW

**Comment by imkiva** [comment]
bors merge

**Comment by imkiva** [comment]
Same problem. 

Why is it taking forever?

_Originally posted by @ice1000 in https://github.com/aya-prover/aya-vscode/issues/10#issuecomment-946291265_

**Comment by imkiva** [comment]
image

where's `gradle` in these copied files?

**Comment by imkiva** [comment]
bors cancel

**Comment by imkiva** [comment]
> Build succeeded:
> 
> * [cargo-check](https://github.com/imkiva/valheim/runs/5714502652?check_suite_focus=true)

Thanks!

**Comment by ice1000** [comment]
> > Build succeeded:
> > 
> > * [cargo-check](https://github.com/imkiva/valheim/runs/5714502652?check_suite_focus=true)
> 
> Thanks!

LMAO

**Comment by imkiva** [comment]
> > > Build succeeded:
> > > 
> > > * [cargo-check](https://github.com/imkiva/valheim/runs/5714502652?check_suite_focus=true)
> > 
> > 
> > Thanks!
> 
> LMAO

经 典 复 刻

**Pull request merged**
